<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-07-22T04:39:02Z" name="Package Test Suit" finished-at="2021-07-22T04:39:03Z" duration-ms="533">
    <groups>
    </groups>
    <test started-at="2021-07-22T04:39:02Z" name="Package Test" finished-at="2021-07-22T04:39:03Z" duration-ms="533">
      <class name="com.qa.test.reqres.LoginTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.qa.test.reqres.LoginTest@4961f6af]" started-at="2021-07-22T12:39:02Z" name="setUp" finished-at="2021-07-22T12:39:02Z" duration-ms="7" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="testStart(java.lang.reflect.Method)[pri:0, instance:com.qa.test.reqres.LoginTest@4961f6af]" started-at="2021-07-22T12:39:02Z" name="testStart" finished-at="2021-07-22T12:39:02Z" duration-ms="10" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.qa.test.reqres.LoginTest.LoginTest(java.lang.String,java.lang.String,int,java.lang.String) throws java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testStart -->
        <test-method signature="LoginTest(java.lang.String, java.lang.String, int, java.lang.String)[pri:0, instance:com.qa.test.reqres.LoginTest@4961f6af]" started-at="2021-07-22T12:39:02Z" name="LoginTest" data-provider="LoginTestData" finished-at="2021-07-22T12:39:03Z" duration-ms="474" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[eve.holt@reqres.in]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[cityslicka]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[200]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[QpwL5tke4Pnpja7X4]]>
              </value>
            </param>
          </params>
          <exception class="org.apache.http.client.ClientProtocolException">
            <full-stacktrace>
              <![CDATA[org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.qa.util.HttpClientUtils.post(HttpClientUtils.java:60)
	at com.qa.test.reqres.LoginTest.LoginTest(LoginTest.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: org.apache.http.ProtocolException: Target host is not specified
	at org.apache.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:71)
	at org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:125)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	... 17 more
]]>
            </full-stacktrace>
          </exception> <!-- org.apache.http.client.ClientProtocolException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTest -->
        <test-method is-config="true" signature="clean()[pri:0, instance:com.qa.test.reqres.LoginTest@4961f6af]" started-at="2021-07-22T12:39:03Z" name="clean" finished-at="2021-07-22T12:39:03Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clean -->
      </class> <!-- com.qa.test.reqres.LoginTest -->
      <class name="com.qa.test.reqres.GetListUsersTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.qa.test.reqres.GetListUsersTest@394df057]" started-at="2021-07-22T12:39:02Z" name="setUp" finished-at="2021-07-22T12:39:02Z" duration-ms="7" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="testStart(java.lang.reflect.Method)[pri:0, instance:com.qa.test.reqres.GetListUsersTest@394df057]" started-at="2021-07-22T12:39:02Z" name="testStart" finished-at="2021-07-22T12:39:02Z" duration-ms="10" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.qa.test.reqres.GetListUsersTest.getListUsersTest(int,int) throws java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testStart -->
        <test-method signature="getListUsersTest(int, int)[pri:0, instance:com.qa.test.reqres.GetListUsersTest@394df057]" started-at="2021-07-22T12:39:02Z" name="getListUsersTest" data-provider="getListUsersTestData" finished-at="2021-07-22T12:39:03Z" duration-ms="474" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[200]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
          </params>
          <exception class="org.apache.http.client.ClientProtocolException">
            <full-stacktrace>
              <![CDATA[org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.qa.util.HttpClientUtils.get(HttpClientUtils.java:27)
	at com.qa.test.reqres.GetListUsersTest.getListUsersTest(GetListUsersTest.java:35)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: org.apache.http.ProtocolException: Target host is not specified
	at org.apache.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:71)
	at org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:125)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	... 17 more
]]>
            </full-stacktrace>
          </exception> <!-- org.apache.http.client.ClientProtocolException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getListUsersTest -->
        <test-method is-config="true" signature="clean()[pri:0, instance:com.qa.test.reqres.GetListUsersTest@394df057]" started-at="2021-07-22T12:39:03Z" name="clean" finished-at="2021-07-22T12:39:03Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clean -->
      </class> <!-- com.qa.test.reqres.GetListUsersTest -->
    </test> <!-- Package Test -->
  </suite> <!-- Package Test Suit -->
</testng-results>
